#!/usr/bin/env python
'''pgdocgen starting point'''

import sys
from getopt import getopt

from pgdocgen.parser import Parser
from pgdocgen.files import read_dir
from pgdocgen.output import HtmlGenerator

def process_file(jdoc):
    '''Function to be called on each source file.
       It parses file and generates JDOC objects'''
    def process_int(s):
        '''internal process_file without jdoc parameter'''
        
        p = Parser()
        r = p.parse(s)
        global jdoc
        jdoc = jdoc + r
    return process_int

if __name__=='__main__':
    '''main'''
    optlist, args = getopt(sys.argv,'x',[])
    input_dir = args[1]
    input_ext = args[2]
    output_dir = args[3]
    project_name = args[4]
    jdoc = []

    read_dir(input_dir,input_ext,process_file(jdoc))
    #from ddlobject.db import DB
    #db = DB('dbname=hr user=hr port=5432 password=hr host=127.0.0.1')

    g = HtmlGenerator(project_name)
    g.write_files(jdoc,output_dir)

